### ISSUE TITLE
xDafnyServer not started

### ISSUE THREAD

**Issue by jkuehnemundt** [ferry-/dafny-vscode#2]
DafnyServer process quit unexpectedly; attempting restart
OS: MacOS

**Comment by pyrolitic** [comment]
Did the dafny server work at all? Did it quit when you saved the file?

**Comment by jkuehnemundt** [comment]
No, it didn't work.
I have used the following settings:

`{
    "dafny.dafnyServerPath": "~/dafny/DafnyServer.exe",
    "dafny.automaticVerification": true,
    "dafny.useMono": true,
    "dafny.monoPath": "/usr/local/bin/mono"
}`

**Comment by pyrolitic** [comment]
Please set `automaticVerification` to `false` and try writing the path without `~`. I mean use the full absolute path, which should be `/Users/<user>/dafny/DafnyServer.exe`.

**Comment by jkuehnemundt** [comment]
I overlooked to use an absolute path.
Now it works, thanks.
